const preguntas = [
  "¿Qué hace el método `Math.random()` en JavaScript?",
  "¿Para qué se utiliza `Math.floor()`?",
  "¿Cuál es la función de `document.querySelector()`?",
  "¿Cómo puedes obtener un elemento del DOM por su ID?",
  "¿Qué hace `element.textContent`?",
  "¿Qué método se utiliza para obtener el valor de un campo de entrada en JavaScript?",
  "¿Cuál es la función de `.toUpperCase()`?",
  "¿Qué hace el método `.split()`?",
  "¿Qué estructura de control utilizas para recorrer un array?",
  "¿Cuál es la función de `element.addEventListener()`?",
  "¿Cómo puedes concatenar dos cadenas en JavaScript?",
  "¿Qué hace el método `.push()` en un array?",
  "¿Qué etiqueta HTML se utiliza para crear un div que muestre los resultados de la calculadora?",
  "¿Cuáles son los números que se pueden ingresar en una calculadora básica?",
  "¿Qué operadores básicos se deben incluir en una calculadora?",
  "¿Cuál es la función de un botón 'C' en una calculadora?",
  "¿Cómo se inicializa el archivo JavaScript para la calculadora?",
  "¿Qué método se usa para capturar clics en los botones de la calculadora?",
  "¿Cómo se muestra el valor de un botón en la consola?",
  "¿Cómo se asigna el valor de un botón a la pantalla de la calculadora?",
  "¿Qué propiedad se usa para cambiar el contenido de texto dentro de un div?",
  "¿Qué variable almacena la concatenación de números ingresados en la calculadora?",
  "¿Cómo se agregan operadores a la variable `entradaActual`?",
  "¿Qué función evalúa una cadena como una operación matemática?",
  "¿Cómo se captura el resultado de una operación en una calculadora?",
  "¿Qué acción realiza el botón 'C' en la calculadora?",
  "¿Cómo se resetea la pantalla de la calculadora a 0?",
  "¿Qué es un bloque try-catch y para qué se usa en la calculadora?",
  "¿Cómo se muestran los errores en la consola y en la pantalla de la calculadora?",
  "¿Qué método permite agregar un evento de clic a un botón en JavaScript?",
  "¿Cómo se concatena el valor de un número en una operación sin sobrescribir el valor anterior?",
  "¿Qué función se usa para verificar que una operación sea válida antes de mostrar el resultado?",
  "¿Cómo se genera un número aleatorio entre 0 y 50 usando `Math.random()`?",
  "¿Qué función redondea hacia abajo un número decimal en JavaScript?",
  "¿Qué método se usa para seleccionar un elemento HTML por su ID?",
  "¿Cómo se cambia el contenido HTML de un elemento seleccionado con `innerHTML`?",
  "¿Cómo se crea un array en JavaScript?",
  "¿Qué es un array bidimensional y cómo se usa?",
  "¿Cómo se accede a un elemento específico dentro de un array bidimensional?",
  "¿Qué es una función en JavaScript y cuál es su propósito?",
  "¿Cómo se define una función que devuelve un saludo personalizado?",
  "¿Cómo se agrega un evento de clic a un botón con `addEventListener()`?",
  "¿Qué es un condicional if-else y cómo funciona?",
  "¿Cómo se verifica si una variable está vacía en JavaScript?",
  "¿Qué método de JavaScript alterna la visibilidad de un div en la pantalla?",
  "¿Qué propiedad se usa para mostrar un div oculto en la pantalla?",
  "¿Qué propiedad se usa para ocultar un div visible?",
  "¿Cómo se alterna la clase CSS de un elemento usando `classList.toggle()`?",
  "¿Qué es el método `classList.add()` y cómo se usa?",
  "¿Qué es el método `classList.remove()` y cuándo se utiliza?",
  "¿Cómo se seleccionan todos los elementos con una clase específica usando `querySelectorAll()`?",
  "¿Qué diferencia hay entre `querySelector()` y `querySelectorAll()`?",
  "¿Cómo se obtiene el valor de un atributo de un elemento con `getAttribute()`?",
  "¿Cómo se establece un nuevo valor a un atributo HTML con `setAttribute()`?",
  "¿Cómo se elimina un atributo HTML de un elemento con `removeAttribute()`?",
  "¿Cómo se comprueba si un elemento tiene un atributo específico usando `hasAttribute()`?",
  "¿Qué hace el método `push()` en un array?",
  "¿Cómo elimina el último elemento de un array el método `pop()`?",
  "¿Cómo se elimina el primer elemento de un array usando `shift()`?",
  "¿Cómo se agrega un elemento al principio de un array con `unshift()`?",
  "¿Qué hace el método `splice()` en un array?",
  "¿Cómo se recorre un array utilizando `forEach()`?",
  "¿Qué devuelve el método `map()` cuando se usa en un array?",
  "¿Cómo se filtran elementos de un array usando `filter()`?",
  "¿Qué método de array suma todos los valores usando `reduce()`?",
  "¿Cómo se genera un número aleatorio entre dos valores con `Math.random()`?",
  "¿Qué tipo de dato devuelve `Math.random()`?",
  "¿Cómo se accede al primer elemento de un array?",
  "¿Cómo se accede al último elemento de un array?",
  "¿Qué es el DOM y cómo se manipula en JavaScript?",
  "¿Qué método selecciona el primer elemento que coincide con un selector CSS?",
  "¿Qué diferencia hay entre `innerHTML` y `textContent`?",
  "¿Cómo se crean variables en JavaScript?",
  "¿Qué es un bucle `for` y para qué se utiliza?",
  "¿Cómo se accede a cada elemento de un array dentro de un bucle `for`?",
  "¿Cómo se comprueba si un número es par o impar usando un condicional `if`?",
  "¿Cómo se define una variable constante en JavaScript?",
  "¿Qué significa `NaN` en JavaScript?",
  "¿Cómo se utiliza `console.log()` para depurar código?",
  "¿Qué es una excepción en JavaScript y cómo se maneja con `try-catch`?",
  "¿Cómo se compara la igualdad de dos valores en JavaScript?",
  "¿Qué es el `localStorage` y cómo se usa para guardar datos?",
  "¿Qué propiedad de CSS oculta un elemento de la vista?",
  "¿Cómo se detiene la propagación de un evento con `event.stopPropagation()`?",
  "¿Cómo se previene el comportamiento por defecto de un evento con `event.preventDefault()`?",
  "¿Qué diferencia hay entre `let` y `var` en JavaScript?",
  "¿Cómo se define un objeto en JavaScript?",
  "¿Cómo se accede a una propiedad de un objeto en JavaScript?",
  "¿Qué es una expresión regular y cómo se usa para validar entradas?",
  "¿Cómo se convierte una cadena de texto a un número en JavaScript?",
  "¿Cómo se redondea un número a un número entero en JavaScript?",
  "¿Qué hace el método `join()` en un array?",
  "¿Cómo se combina el contenido de dos arrays usando `concat()`?",
  "¿Qué método devuelve una nueva copia de un array con un rango de elementos usando `slice()`?",
  "¿Qué es un callback en JavaScript?",
  "¿Cómo se detiene la ejecución de una función usando `return`?",
  "¿Qué significa `undefined` en JavaScript?",
  "¿Cómo se ejecuta un bloque de código después de un tiempo determinado usando `setTimeout()`?",
  "¿Qué hace `clearTimeout()` en JavaScript?",
  "¿Cómo se repite una función en intervalos de tiempo usando `setInterval()`?",
  "¿Qué es el `this` en JavaScript y a qué hace referencia?",
  "¿Cómo se clona un array en JavaScript sin modificar el original?",
  "¿Qué es la coerción de tipos en JavaScript?",
  "¿Cómo se ejecuta código asincrónico usando `async` y `await`?",
  "¿Cómo se envía una solicitud HTTP usando `fetch()` en JavaScript?",
  "¿Qué método se usa para convertir un objeto a formato JSON en JavaScript?",
  "¿Cómo se maneja una promesa rechazada con `catch()`?",
  "¿Cómo se usa `finally()` en una promesa para ejecutar código después de que se resuelva o rechace?",
];

function exportToExcel() {
  // Crear una hoja de cálculo (worksheet) con el array de preguntas
  const ws = XLSX.utils.json_to_sheet(preguntas.map((p) => ({ Pregunta: p })));

  // Crear un libro de trabajo (workbook) y agregar la hoja de cálculo
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Preguntas");

  // Descargar el archivo Excel
  XLSX.writeFile(wb, "preguntas.xlsx");
}

// Asignar el evento al botón
document.getElementById("exportExcel").addEventListener("click", exportToExcel);
